# Generated by Django 4.0.6 on 2022-11-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliate',
            name='downline',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deposits',
            name='amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deposits',
            name='mpesa_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deposits',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deposits',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='investments',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='amount',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='affiliate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='investments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
