# Generated by Django 4.0.6 on 2022-11-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_affiliate_downline_affiliate_username_clients_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clients'),
        ),
        migrations.AlterField(
            model_name='deposits',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clients'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clients'),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.clients'),
        ),
    ]
