# Generated by Django 4.0.6 on 2022-11-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_investments_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investments',
            old_name='STATUS',
            new_name='status',
        ),
        migrations.AddField(
            model_name='investments',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
